### ISSUE TITLE
Use xattr (extended attributes) to save/load text encoding with file 

### ISSUE THREAD

**Issue by gingerbeardman** [textmate/requests#7]
# Proposal
Use xattr (extended attributes) on macOS to save/load text encoding with file.

> BBEdit is the only editor I've found that already does this.

TM already honours any existing `com.apple.TextEncoding` and keeps it when saving.

## Background
- Text Encoding has to either be set manually, or guessed by scanning the file
- Both of these tasks take time

## Benefits
- loading time can be reduced
- encoding dialog can be skipped
- text encoding can be persistent
- can still be changed and rewritten at any point

### Details
debug command:
`xattr -p -l com.apple.TextEncoding "/path/to/file.txt"`

output:
`file.txt`
`com.apple.TextEncoding: Shift_JIS;2561`

to set xattr (from terminal):
`xattr -w com.apple.TextEncoding "Shift_JIS;2561" "/path/to/file.txt"`

### References

these may help with implementation:
- obj-c: https://stackoverflow.com/questions/10374580/
- swift: https://github.com/okla/swift-xattr
- obj-c & swift (alt): https://developer.apple.com/library/content/qa/qa1719/_index.html 

- TextMate Version: 2.0-rc.8
- OS Version: 10.13.3

**Comment by sorbits** [comment]
TextMate already reads this attribute.

It doesn’t write it both because the attribute was (when I added support) not properly documented, so didn’t want to create potentially invalid data for a semi-private Apple attribute, and because I do not believe that new files should be written using legacy encodings, and for UTF-8, there is no need to add this attribute, as UTF-8 files can already be detected without issues.

You are however welcome to submit a pull request where this is *conditionally* enabled for writing files, assuming you can find proper documentation for what values to use for this attribute.

**Comment by gingerbeardman** [comment]
Thanks for your thoughts.

I'm working with legacy OSS files in Shift_JIS. I appreciate that new files should not default to be written with legacy encodings. But I often have to create a new legacy Shift_JIS file, I do so by changing the encoding at save time in the file selector. I hoped TextMate would respect that choices and make my life easier by not asking me what encoding the file is every time I open it?

Values are standard Core Foundation encodings `name;id` https://developer.apple.com/documentation/corefoundation/cfstring/external_string_encodings
https://developer.apple.com/documentation/corefoundation/cfstringbuiltinencodings

Sample code:
https://gist.github.com/mwaterfall/543667/9914a67543c5b84b1a70bcf2e069c4e96ab401a9

**Comment by sorbits** [comment]
You can set default encoding for new files via .tm_properties.

IMHO better, because then you specifically say that e.g. all *.txt files 
saved under vendor/legacy should be Shift_JIS rather than do it on a 
file-by-file basis.
